version: '3.7'
services:
  pulsar-broker:
    image: apachepulsar/pulsar:latest
    command: bin/pulsar standalone
    ports:
      - 6650:6650
      - 8080:8080
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  producer:
    image: pulsar-producer
    command: python3 /app/producer.py
    environment:
      - BROKER_IP=pulsar-broker
      - API_TOKEN=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
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  consumer:
    image: pulsar-consumer
    command: python3 /app/consumer.py
    environment:
      - BROKER_IP=pulsar-broker
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
